// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1itx5D6QdEdB--4YeCXHFPHgDhQkYqI',
    appId: '1:550305118099:web:df92bfa669b2e882ba9a66',
    messagingSenderId: '550305118099',
    projectId: 'altarlink-fa21c',
    authDomain: 'altarlink-fa21c.firebaseapp.com',
    storageBucket: 'altarlink-fa21c.firebasestorage.app',
    measurementId: 'G-M8P8HS726N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZBwMu-LzGB03XppGXdHfcWP23Ryo4Jc',
    appId: '1:550305118099:android:2003088473d517e1ba9a66',
    messagingSenderId: '550305118099',
    projectId: 'altarlink-fa21c',
    storageBucket: 'altarlink-fa21c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0G_nlVdtdmnp_w6hMt-yjVbCLSKbNgDY',
    appId: '1:550305118099:ios:c027324ccce97fa4ba9a66',
    messagingSenderId: '550305118099',
    projectId: 'altarlink-fa21c',
    storageBucket: 'altarlink-fa21c.firebasestorage.app',
    iosBundleId: 'com.example.altarlink4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0G_nlVdtdmnp_w6hMt-yjVbCLSKbNgDY',
    appId: '1:550305118099:ios:c027324ccce97fa4ba9a66',
    messagingSenderId: '550305118099',
    projectId: 'altarlink-fa21c',
    storageBucket: 'altarlink-fa21c.firebasestorage.app',
    iosBundleId: 'com.example.altarlink4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ1itx5D6QdEdB--4YeCXHFPHgDhQkYqI',
    appId: '1:550305118099:web:5f1771568b28f43bba9a66',
    messagingSenderId: '550305118099',
    projectId: 'altarlink-fa21c',
    authDomain: 'altarlink-fa21c.firebaseapp.com',
    storageBucket: 'altarlink-fa21c.firebasestorage.app',
    measurementId: 'G-3FYMD0PCBP',
  );
}
